### ISSUE TITLE
Great plugin, works great but I keep getting this is console

### ISSUE THREAD

**Issue by Antisa14200** [TheLukeGuy/JustWorlds#1] opened 2018-03-04 11:31 UTC
Could not pass event PlayerChangedWorldEvent to JustWorlds v1.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:719) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.PlayerList.changeDimension(PlayerList.java:783) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:618) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.Entity.postTick(Entity.java:346) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1632) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:688) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1403) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-3a482bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at net.lukepchambers.justworlds.Main.onWorldChange(Main.java:718) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4bd94dc-3a482bd]
        ... 17 more

**Comment by TheLukeGuy** [comment] 2018-03-04 11:43
Thanks for using JustWorlds!

Which Minecraft version is the server running on? I seemed to get that often when running servers with 1.11.2 or below.

**Comment by Antisa14200** [comment] 2018-03-04 11:53
1.12.2 latest version of Spigot

Dana 4. ožu 2018. 12:43 osoba "Luke Chambers" <notifications@github.com>
napisala je:

**Comment by TheLukeGuy** [comment] 2018-03-04 12:19
Hm, interesting. I haven't seen this while I was testing.

Could you just answer a few questions quickly? These will just help me find out _why_ this is happening.

1. What are the steps to reproduce the error?
2. What was supposed to happen when the error was thrown?
3. What actually happened?
4. What Java version and OS are you running?

Thanks! 😄

**Comment by Antisa14200** [comment] 2018-03-04 13:30
Can I just ask you something to make sure
How can I migrate unmigrated existing worlds?
Like world_nether, world_the_end and world (spawn) ?

**Comment by TheLukeGuy** [comment] 2018-03-04 14:42
You can just use /jwcreate as if you were creating those worlds.

**world** - `/jwcreate world`
**world_nether** - `/jwcreate world_nether nether`
**world_the_end** - `/jwcreate world_the_end the_end`

**Comment by TheLukeGuy** [comment] 2018-03-04 14:46
Anyway, try the .jar file below. I think I've fixed the bug– if it seems to be working correctly now for you I'll release an update on SpigotMC.

[JustWorlds.jar.zip](https://github.com/TheLukeGuy/JustWorlds/files/1778586/JustWorlds.jar.zip)

**Comment by Antisa14200** [comment] 2018-03-04 14:52
Btw how can I do /jwcreate world if world already exists? Same for world_the_end and world_nether?

**Comment by TheLukeGuy** [comment] 2018-03-04 15:07
Oh, that's another bug, I have to allow the default to be migrated in the latest update.

I'll try to fix that bug in the next update but for now you'll probably have to downgrade the plugin to version 1.1.1 to be able to migrate those worlds for now. I'm going to most likely release a fix for that in an hour or so, though.

**Comment by Antisa14200** [comment] 2018-03-04 15:10
Yeah, allowing unmigrated worlds which are already added to get migrated would be great

**Comment by TheLukeGuy** [comment] 2018-03-04 16:46
Both bugs have been fixed in [version 1.4](https://www.spigotmc.org/resources/%E2%98%86-justworlds-%C2%BB-create-and-manage-worlds-easily.53792/update?update=214584).

58a5b4b
6c4311b

Thanks for reporting! :)

**Closed by TheLukeGuy** 2018-03-04 16:46 UTC
Labels: bug

**Comment by Antisa14200** [comment] 2018-03-04 17:08
@TheLukeGuy Where can I get a AutoUpdaterAPI plugin for updating JustWorlds?

**Comment by TheLukeGuy** [comment] 2018-03-04 17:56
Just search for AutoUpdaterAPI, it's a plugin on SpigotMC. 😄

**Comment by Antisa14200** [comment] 2018-03-04 18:00
https://www.spigotmc.org/resources/autoupdaterapi.39719/ this one?

**Comment by Antisa14200** [comment] 2018-03-04 20:12
Alright, thanks!
Btw, on the server, message "The plugin is already up-to-date." shouldn't be a error.
Just letting you know :D

**Comment by Antisa14200** [comment] 2018-03-04 22:12
@TheLukeGuy 1 more question
When we add another custom world or map on your server, it can't be migrated since it's not allowed world, world with that name already exists.
So are you able to make it allow to migrate another custom world/map which we add?

**Comment by TheLukeGuy** [comment] 2018-03-04 22:54
Oh, yeah, I'll have to find a fix for that too but for now you can restart your server and you should be able to migrate them.

**Comment by TheLukeGuy** [comment] 2018-03-05 00:24
I've fixed this bug in [version 1.5](https://www.spigotmc.org/resources/%E2%98%86-justworlds-%C2%BB-create-and-manage-worlds-easily.53792/update?update=214681). 😄

b75a100

**Comment by Antisa14200** [comment] 2018-03-05 13:52
When you type /jwhelp there's nothing 
--------- Help: JustWorlds ----------------------
[14:52:27 INFO]: Below is a list of all JustWorlds commands:

**Comment by Antisa14200** [comment] 2018-03-05 13:55
Also btw a suggestion, feature for renaming worlds which are migrated, if possible?

**Comment by TheLukeGuy** [comment] 2018-03-09 17:41
1. I'm aware of the /jwhelp issue, I'm trying my best to fix it by tomorrow. :)
2. I'll try to add renaming worlds, thanks for the suggestion!

**Comment by TheLukeGuy** [comment] 2018-03-09 20:41
I've fixed the /jwhelp issue in [version 1.6](https://www.spigotmc.org/resources/%E2%98%86-justworlds-%C2%BB-create-and-manage-worlds-easily.53792/update?update=215397). :)

c82e2d2

**Comment by Antisa14200** [comment] 2018-03-09 20:45
Great
Look up my suggestion when you are able to :)

**Comment by TheLukeGuy** [comment] 2018-03-09 23:12
I definitely will, it'll be a bit tricky to do it with migrated worlds but I'll try my best. :)

**Comment by Antisa14200** [comment] 2018-03-10 05:27
Alright thanks

sub, 10. ožu 2018. 00:12 Luke Chambers <notifications@github.com> je
napisao:

**Comment by Antisa14200** [comment] 2018-03-17 19:49
Is the latest version safe to use? Because I have 1.7.2

**Comment by Antisa14200** [comment] 2018-03-17 21:25
Oh ok bcs on 1.7.3 you said not to use it it breaks plugin

sub, 17. ožu 2018. 22:22 Luke Chambers <notifications@github.com> je
napisao:

**Comment by TheLukeGuy** [comment] 2018-03-17 21:35
Oh 🤣 did you see that in one of the latest commits? All of the broken elements from that commit were fixed in the latest commit.

**Comment by Antisa14200** [comment] 2018-03-17 21:37
Oh k thanks lol 🤣
